import NextLink from 'next/link';
import { Button } from '@heroui/button';
import { Chip } from '@heroui/chip';
import { tv } from 'tailwind-variants';
import { title, subtitle } from '@/sharedComponents/primitives';

const clayCard = tv({
  base: 'relative overflow-hidden rounded-3xl p-8 border-2 backdrop-blur-sm',
  variants: {
    color: {
      blue: 'bg-blue-500/10 border-blue-400/30 shadow-[0_8px_32px_rgba(37,99,235,0.25),inset_0_-3px_0_rgba(37,99,235,0.4)]',
      cyan: 'bg-cyan-500/10 border-cyan-400/30 shadow-[0_8px_32px_rgba(6,182,212,0.25),inset_0_-3px_0_rgba(6,182,212,0.4)]',
      violet:
        'bg-violet-500/10 border-violet-400/30 shadow-[0_8px_32px_rgba(139,92,246,0.25),inset_0_-3px_0_rgba(139,92,246,0.4)]',
    },
  },
  defaultVariants: { color: 'blue' },
});

const FEATURE_CARDS = [
  {
    color: 'blue' as const,
    icon: '🤖',
    heading: 'AI-Generated Questions',
    body: 'Every question is generated by a large language model trained on real exam material — fresh, non-repetitive practice every session.',
  },
  {
    color: 'cyan' as const,
    icon: '🎯',
    heading: 'Real Exam Topics',
    body: 'Questions are scoped to official exam domains and weighted by topic coverage so you practice what actually appears on the test.',
  },
  {
    color: 'violet' as const,
    icon: '📊',
    heading: 'Track Your Progress',
    body: 'Answers are saved locally so you can resume sessions and see which topics need more attention before exam day.',
  },
] as const;

const CERTIFICATIONS = [
  { label: 'AWS', color: 'warning' },
  { label: 'Azure', color: 'primary' },
  { label: 'GCP', color: 'success' },
  { label: 'SAP', color: 'secondary' },
  { label: 'CompTIA', color: 'danger' },
  { label: 'Kubernetes', color: 'default' },
  { label: 'Terraform', color: 'secondary' },
  { label: 'Linux+', color: 'default' },
] as const;

export default function HeroPage() {
  return (
    <div className="bg-[#0a1628] text-white">
      <HeroSection />
      <FeaturesSection />
      <CertificationsSection />
      <CtaSection />
    </div>
  );
}

function HeroSection() {
  return (
    <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden px-6">
      <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-blue-600/20 rounded-full blur-3xl pointer-events-none -translate-x-1/2 -translate-y-1/2" />
      <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-cyan-500/15 rounded-full blur-3xl pointer-events-none translate-x-1/2 translate-y-1/2" />

      <div className="relative z-10 flex flex-col items-center text-center max-w-4xl mx-auto gap-6">
        <Chip
          color="primary"
          variant="flat"
          radius="full"
          className="text-xs tracking-widest uppercase font-semibold px-4"
        >
          AI-Powered Exam Prep
        </Chip>

        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold leading-tight">
          <span className={title({ color: 'cyan', size: 'lg' })}>Ace your </span>
          <span className={title({ color: 'blue', size: 'lg' })}>certification</span>
          <br />
          <span className="text-white">with AI-generated questions</span>
        </h1>

        <p className={subtitle()}>
          Practice for AWS, Azure, GCP, SAP, CompTIA and more. Every quiz is uniquely generated — no outdated question
          banks.
        </p>

        <div className="flex flex-wrap gap-4 justify-center mt-2">
          <Button
            as={NextLink}
            href="/quiz"
            color="primary"
            size="lg"
            radius="full"
            className="font-semibold px-8 shadow-[0_4px_24px_rgba(37,99,235,0.5)]"
          >
            Start Practicing Free
          </Button>
          <Button
            as={NextLink}
            href="/configure-certification"
            variant="bordered"
            size="lg"
            radius="full"
            className="font-semibold px-8 border-blue-400/50 text-blue-300"
          >
            Configure Certifications
          </Button>
        </div>
      </div>
    </section>
  );
}

function FeaturesSection() {
  return (
    <section className="py-24 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <h2 className={title({ size: 'md' })}>Why AIQUIZ?</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {FEATURE_CARDS.map((card) => (
            <div key={card.heading} className={clayCard({ color: card.color })}>
              <div className="text-4xl mb-4">{card.icon}</div>
              <h3 className="text-xl font-bold text-white mb-3">{card.heading}</h3>
              <p className="text-zinc-400 leading-relaxed">{card.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CertificationsSection() {
  return (
    <section className="py-16 px-6">
      <div className="max-w-4xl mx-auto text-center">
        <h2 className="text-2xl font-bold text-zinc-300 mb-10">Supported Certifications</h2>
        <div className="flex flex-wrap justify-center gap-4">
          {CERTIFICATIONS.map((cert) => (
            <Chip
              key={cert.label}
              color={cert.color}
              variant="flat"
              size="lg"
              radius="full"
              className="text-sm font-semibold px-4 py-5 border border-current/20"
            >
              {cert.label}
            </Chip>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaSection() {
  return (
    <section className="py-24 px-6">
      <div className="max-w-3xl mx-auto">
        <div className={clayCard({ color: 'cyan' })}>
          <div className="absolute inset-0 rounded-3xl overflow-hidden pointer-events-none">
            <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-400/10 rounded-full blur-3xl" />
          </div>
          <div className="relative z-10 flex flex-col items-center text-center gap-6 py-6">
            <h2 className="text-3xl lg:text-4xl font-extrabold text-white">Ready to pass your next exam?</h2>
            <p className="text-zinc-400 max-w-lg">
              Configure your target certification, pick your topics, and let AI build a custom practice session in
              seconds.
            </p>
            <Button
              as={NextLink}
              href="/quiz"
              color="primary"
              size="lg"
              radius="full"
              className="font-semibold px-10 shadow-[0_4px_24px_rgba(6,182,212,0.4)]"
            >
              Generate My First Quiz
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}
