export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "AIQuiz",
  description: "AI-powered certification exam prep. Practice AWS, Azure, GCP, SAP, and CompTIA questions generated by AI.",
  navItems: [
    {
      label: "Generate Questions",
      href: "/generate-questions",
    },
    {
      label: "Configure Certification",
      href: "/configure-certification",
    },
    {
      label: "Make your own quiz",
      href: "/quiz",
    }
  ],
  navMenuItems: [
    {
      label: "Quiz",
      href: "/quiz",
    },
    {
      label: "Generate Questions",
      href: "/generate-questions",
    },
    {
      label: "Configure Certification",
      href: "/configure-certification",
    },
  ],
  links: {
    github: "https://github.com/GuiHolanda/quiz-maker/tree/main",
    docs: "https://heroui.com",
  },
};
