export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: 'Certifique AI',
  description:
    'AI-powered certification exam prep. Practice AWS, Azure, GCP, SAP, and CompTIA questions generated by AI.',
  navItems: [
    {
      label: 'nav.questions',
      href: '/certifications/questions',
    },
    {
      label: 'nav.configureCertification',
      href: '/certifications/configure',
    },
    {
      label: 'nav.makeYourOwnQuiz',
      href: '/simulados',
    },
  ],
  navMenuItems: [
    {
      label: 'nav.quiz',
      href: '/simulados',
    },
    {
      label: 'nav.questions',
      href: '/certifications/questions',
    },
    {
      label: 'nav.configureCertification',
      href: '/certifications/configure',
    },
  ],
  links: {
    github: 'https://github.com/GuiHolanda/quiz-maker/tree/main',
    docs: 'https://heroui.com',
  },
};
