export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "AIQuiz",
  description: "AI-powered certification exam prep. Practice AWS, Azure, GCP, SAP, and CompTIA questions generated by AI.",
  navItems: [
    {
      label: "nav.generateQuestions",
      href: "/certifications/generate",
    },
    {
      label: "nav.configureCertification",
      href: "/certifications/configure",
    },
    {
      label: "nav.makeYourOwnQuiz",
      href: "/certifications/quiz",
    },
    {
      label: "nav.browseQuestions",
      href: "/certifications/browse",
    },
  ],
  navMenuItems: [
    {
      label: "nav.quiz",
      href: "/certifications/quiz",
    },
    {
      label: "nav.generateQuestions",
      href: "/certifications/generate",
    },
    {
      label: "nav.configureCertification",
      href: "/certifications/configure",
    },
    {
      label: "nav.browseQuestions",
      href: "/certifications/browse",
    },
  ],
  links: {
    github: "https://github.com/GuiHolanda/quiz-maker/tree/main",
    docs: "https://heroui.com",
  },
};
