import { NextRequest, NextResponse } from 'next/server';
import { QuestionService } from '@/app/api/question-generator/question.service';
import { OpenAIService } from '@/features/services/openAI.service';
import { Templates } from '@/config/constants/templates';
const questionService = new QuestionService();
const openAIService = new OpenAIService();
const responseCache = "{\"id\":\"Q1\",\"question\":\"In SAP Commerce Cloud Product Content Management, how is product content localization typically handled?\",\"options\":[{\"label\":\"A\",\"text\":\"Product content is stored only in the base language and must be duplicated manually for each target language.\"},{\"label\":\"B\",\"text\":\"PCM supports multi-language product content by using language variants and translation workflows integrated with the Backoffice.\"},{\"label\":\"C\",\"text\":\"Translations are automatically generated by the system without human validation.\"},{\"label\":\"D\",\"text\":\"Localization requires a separate PCM instance for each language.\"},{\"label\":\"E\",\"text\":\"Localization data is managed only in SmartEdit and not stored in PCM.\"}],\"correctAnswers\":[\"B\"],\"explanation\":\"The Backoffice PCM supports multi-language data using language variants and translation workflows to manage translations. Other options describe inaccurate or incomplete localization approaches in SAP Commerce Cloud PCM. Two or more sentences: The language-variant and translation workflow approach is the standard method for PCM localization. Automatic translation without validation or separate PCM instances are not how PCM localization is designed to work.\",\"sources\":[\"https://www.sap.com/hk/products/crm/commerce-cloud/pcm.html?utm_source=openai\",\"https://learning.sap.com/learning-journeys/creating-and-configuring-web-content-for-sap-commerce-cloud/introducing-smartedit?utm_source=openai\",\"https://community.sap.com/t5/crm-and-cx-blog-posts-by-sap/smartedit-enhancements-in-commerce-cloud-2025-q2-release/ba-p/14135385?utm_source=openai\"]}";

export async function GET(request: NextRequest) {
  debugger
  const questionParams = questionService.getQuestionParams(new URL(request.url));

  try {
    const response = await openAIService.generateQuestions(Templates.GENERATE_QUESTIONS, questionParams);
    const questionsFromAi = questionService.getValidatedQuestions(JSON.parse(response));
    //const shuffledQuestions = questionsFromAi.map((q) => questionService.shuffleQuestionOptions(q));

    return NextResponse.json(questionsFromAi, { status: 200 });
  } catch (err: any) {
    console.error('Failed to process request:', err);
    return NextResponse.json(
      { error: err, message: err.message || 'Failed to process request' },
      { status: err.status || 500 }
    );
  }
}
